version: "3.7"
name: quattro-infrastructure
services:
  postgres:
    image: postgres
    container_name: common.quattro.postgres
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=borda
      - POSTGRES_DB=authorizationdb
      - ALLOW_IP_RANGE='0.0.0.0/0'
      - TZ=Asia/Istanbul
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    networks:
      - common_quattro_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: common.quattro.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@bordatech.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-borda}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - "postgres"
    networks:
      - common_quattro_network

  rabbitmq:
    build: ./rabbitmq
    container_name: common.quattro.rabbitmq
    networks:
      - common_quattro_network
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: common.quattro.redis
    networks:
      - common_quattro_network
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: quattro.common.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - common_quattro_network
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongoconfig
        target: /data/configdb

  mongo-express:
    image: mongo-express
    container_name: quattro.common.mongoexpress
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: quattro.common.mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - common_quattro_network
    depends_on:
      - mongo

  minio:
    image: 'quay.io/minio/minio'
    container_name: quattro.common.minio
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    networks:
      - common_quattro_network

networks:
  common_quattro_network:
    name: common-quattro-network

volumes:
  postgresdb:
  pgadmin:
  rabbitmq:
  minio:
  mongodb:
    name: mongodb
  mongoconfig:
    name: mongoconfig

